### ISSUE TITLE
Incorrectly escaped HTML when honeypot_style_class is used

### ISSUE THREAD

**Issue by rchekaluk** [curtis/honeypot-captcha#19]
**Describe the bug**
When `honeypot_style_class` is overridden with a value:
```
def honeypot_style_class
  'classname'
end
```
the resulting form HTML contains invalid escaping, like this:
```
<form method="post"><input name="utf8" type="hidden" value="&#x2713;" /><div id="a_comment_body_hp_1549963167" class="classname">&lt;label for=&quot;a_comment_body&quot;&gt;Do not fill in this field&lt;/label&gt;&lt;input type=&quot;text&quot; name=&quot;a_comment_body&quot; id=&quot;a_comment_body&quot; /&gt;</div>
```

**To Reproduce**
1. Override honeypot_style_class in your application [as described](https://github.com/curtis/honeypot-captcha#customizing-the-honeypot-fields)

**Expected behavior**
Resulting HTML should not contain invalid escaping:
```
<form method="post"><input name="utf8" type="hidden" value="&#x2713;" /><div id="a_comment_body_hp_1549963127" class="classname"><label for="a_comment_body">Do not fill in this field</label><input type="text" name="a_comment_body" id="a_comment_body" /></div>
```

**Comment by curtis** [comment]
@rchekaluk thanks for the bug report and pull request! There should be a 1.0.1 version available now with this fix.
