### ISSUE TITLE
Did this stop working with Rails 4.2?

### ISSUE THREAD

**Issue by cmalpeli** [curtis/honeypot-captcha#8]
It seems like the form field has disappeared once I upgraded.

**Comment by curtis** [comment]
@cmalpeli sorry, I haven't tried it with Rails 4.2 yet, but I'll try to take a look on Friday.

**Comment by Lordnibbler** [comment]
@curtis any updates on this? i too cannot get the honeypot `textarea` to show up in rails 4.2 anymore

**Comment by curtis** [comment]
Thanks to @dukedave for updating this to work with Rails 4.2!
